#+TITLE: linux

* Linux
** distros

*** archlinux
*** debian
** wget

*** 需要下载某个目录下面的所有文件。
命令如下
wget -c -r -np -k -L -p http://docs.openstack.org/liberty/install-guide-rdo/

*** 在下载时。有用到外部域名的图片或连接。如果需要同时下载就要用-H参数。
wget -np -nH -r –span-hosts www.xianren.org/pub/path/
-c 断点续传
-r 递归下载，下载指定网页某一目录下（包括子目录）的所有文件
-nd 递归下载时不创建一层一层的目录，把所有的文件下载到当前目录
-np 递归下载时不搜索上层目录，如wget -c -r www.xianren.org/pub/path/
没有加参数-np，就会同时下载path的上一级目录pub下的其它文件
-k 将绝对链接转为相对链接，下载整个站点后脱机浏览网页，最好加上这个参数
-L 递归时不进入其它主机，如wget -c -r www.xianren.org/
如果网站内有一个这样的链接：
www.xianren.org，不加参数-L，就会像大火烧山一样，会递归下载www.xianren.org网站
-p 下载网页所需的所有文件，如图片等
-A 指定要下载的文件样式列表，多个样式用逗号分隔
-i 后面跟一个文件，文件内指明要下载的URL
** iptables

#+BEGIN_SRC bash
How to set linux server as gateway?

# set ip forward
echo 1 > /proc/sys/net/ipv4/ip_forward
# set iptables, $IF_EXTERNAL is external interface, $EX_EXTERNAL is internal interface
export IF_INTERNAL=
export IF_EXTERNAL=
iptables -t nat -A POSTROUTING -o $IF_EXTERNAL -j MASQUERADE
iptables -A FORWARD -i $IF_INTERNAL -o $IF_EXTERNAL -j ACCEPT
iptables -A FORWARD -i $IF_EXTERNAL -o $IF_INTERNAL -m state --state RELATED,ESTABLISHED -j ACCEPT
#+END_SRC

#+RESULTS:
** ssh

*** -L [bind_address:]port:host:hostport
#+BEGIN_SRC bash
ssh -L 2210:10.53.7.32:22 jump01.bj.sensetime.com
#+END_SRC
*** -R [bind_address:]port:host:hostport
所谓“反向代理”就是让远端启动端口，把远端端口数据转发到本地。
HostA 将自己可以访问的 HostB:PortB 暴露给外网服务器 HostC:PortC，在 HostA 上运行：
那么链接 HostC:PortC 就相当于链接 HostB:PortB。使用时需修改 HostC 的 /etc/ssh/sshd_config，添加：
GatewayPorts yes

#+BEGIN_SRC bash
#ssh -R HostC:PortC:HostB:PortB  user@HostC
ssh -R 10.0.0.254:9999:10.0.0.22:8888 10.0.0.254

#+END_SRC
*** -D [bind_address:]port
在 HostA 的本地 1080 端口启动一个 socks5 服务，通过本地 socks5 代理的数据会通过 ssh 链接先发送给 HostB，再从 HostB 转发送给远程主机：
那么在 HostA 上面，浏览器配置 socks5 代理为 127.0.0.1:1080，看网页时就能把数据通过 HostB 代理出去，类似 ss/ssr 版本，只不过用 ssh 来实现。

#+BEGIN_SRC bash
ssh -D localhost:1080  HostB

#+END_SRC`

*** tunning
为了更好用一点，ssh 后面还可以加上：-CqTnN 参数，比如：
#+BEGIN_SRC bash
ssh -CqTnN -L 0.0.0.0:PortA:HostC:PortC  user@HostB
#+END_SRC
其中 -C 为压缩数据，-q 安静模式，-T 禁止远程分配终端，-n 关闭标准输入，-N 不执行远程命令。此外视需要还可以增加 -f 参数，把 ssh 放到后台运行。
这些 ssh 代理没有短线重连功能，链接断了命令就退出了，所以需要些脚本监控重启，或者使用 autossh 之类的工具保持链接。
** KDE

*** kDE plasma tips
[[https://userbase.kde.org/Plasma/Tips][Plasma/Tips - KDE UserBase Wiki]]
*** windows/meta key
.config/kwinrc

#+BEGIN_SRC text
[ModifierOnlyShortcuts]
Alt=org.kde.kglobalaccel,/component/kwin,,invokeShortcut,Expose
Control=
Meta=org.kde.plasmashell,/PlasmaShell,org.kde.PlasmaShell,activateLauncherMenu
Shift=
#+END_SRC

#+BEGIN_SRC shell
kwriteconfig5 --file ~/.config/kwinrc --group ModifierOnlyShortcuts --key Meta "org.kde.plasmashell,/PlasmaShell,org.kde.PlasmaShell,activateLauncherMenu"
qdbus org.kde.KWin /KWin reconfigure

#+END_SRC

#+RESULTS:

***  set google-chrome as default browser
reference to : http://gregladen.com/blog/2019/02/16/chrome-as-default-browser-in-kde-plasma-getting-it-to-stick/

Go ahead and chose “chromium” as the default browser in the “settings” application, and hit apply. That setting will likely stick, but Chrome will not be the default browser anyway. A bug in KDE Plasma prevents this, but you can drill down deeper into the configuration information and make it work:
Go to your settings tool.
Go to Configure File Associations
Filter the list for “html”
Find the entry for xhtml+xml and move “Chromium” to the top of the list.
Do the same for “html”
Hit “apply.”
Your problem is probably now solved.
** i3

[[https://tunkshif.github.io/linux/i3-config.html][桌面环境微科普与 i3 配置记录]]
*** xrandr
[[https://ubuntuforums.org/showthread.php?t=1112186][{ubuntu} xrandr add screen resolution]]
#+BEGIN_SRC bash
# check maxium buffer
xrandr | grep maximum

# use gtf to create a mode line
gtf 1440 900 59.9

# add new mode using xrandr
xrandr --newmode "1440x900_59.90"  106.29  1440 1520 1672 1904  900 901 904 932  -HSync +Vsync

# add new mode to desired output
xrandr --addmode VGA 1440x900_59.90

# choose new mode
xrandr --output VGA --mode 1440x900_59.90


#+END_SRC
** macbook

*** power management
please refer to [[https://wiki.archlinux.org/index.php/Mac][Mac - ArchWiki]]

*** touchpad
#+BEGIN_SRC
/etc/X11/xorg.conf.d/30-touchpad.conf
Section "InputClass"
    Identifier "touchpad"
    Driver "libinput"
    MatchIsTouchpad "on"
    Option "Tapping" "on"
    Option "TappingButtonMap" "lmr"
EndSection
#+END_SRC

* archlinux

** troubleshoot
when install arch form chroot. you may meet the following issues
https://bbs.archlinux.org/viewtopic.php?id=196615

#+BEGIN_SRC bash
$ ls -la /
drwxr-x---   1 root root  122 Aug 11 16:50 .

So just had to fix it with

$ chmod 755 /



#+END_SRC

* vnc

[[https://faq.i3wm.org/question/2072/how-do-i-get-i3-to-run-over-a-vnc-connection.1.html][How do I get i3 to run over a VNC connection? - i3 FAQ]]

#+BEGIN_SRC shell
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
XDG_SESSION_TYPE=x11;  export XDG_SESSION_TYPE

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid black

#Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

MYIM=fcitx
export GTK_IM_MODULE=$MYIM
export QT_IM_MODULE=$MYIM
export XMODIFIERS=@im=$MYIM
export QT_QPA_PLATFORMTHEME="qt5ct"

vncconfig -nowin &
i3 &

#+END_SRC
