#!/bin/sh

userresources=$HOME/.config/X11/xresources
usermodmap=$HOME/.config/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ -x "$(command -v fcitx5)" ]; then
    echo 'use fcitx5'
    export GTK_IM_MODULE=fcitx5
    export QT_IM_MODULE=fcitx5
    export XMODIFIERS=@im=fcitx5
    fcitx5 &
elif [ -x "$(command -v fcitx)" ]; then
    echo 'use fcitx'
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
    fcitx -dr
elif [ -x "$(command -v ibus-daemon)" ]; then
    echo 'use ibus'
    export GTK_IM_MODULE=xim
    export QT_IM_MODULE=xim
    export XMODIFIERS=@im=ibus
    ibus-daemon -drx
fi

$HOME/.bin/office-desktop.sh
hsetroot -solid "#000000"

export XDG_CURRENT_DESKTOP=KDE
export KDE_SESSION_VERSION=5
export QT_QPA_PLATFORMTHEME="qt5ct"

export _JAVA_AWT_WM_NONREPARENTING=1

#exec dbus-launch --exit-with-session i3
xsetroot -cursor_name left_ptr

exec bspwm
