#+TITLE: Org Mode Configuration
#+AUTHOR: zhoumingjun <zhoumingjun@gmail.com>
#+PROPERTY: header-args :emacs-lisp :tangle yes :comments link :cache yes :padline no :results silent
#+STARTUP: org-startup-folded: showall

** Table of Contents :TOC_3_gh:noexport:
  - [[#reference][Reference]]
  - [[#aesthetic-packages][Aesthetic Packages]]
    - [[#dired-icons][Dired Icons]]
    - [[#wakatime][Wakatime]]
  - [[#org-additions][Org Additions]]
    - [[#org-protocol-updates][Org Protocol Updates]]
    - [[#org-noter][Org Noter]]
    - [[#org-kankan][Org kankan]]
    - [[#org-http][Org http]]
    - [[#org-roam][Org Roam]]
    - [[#org-rifle][Org Rifle]]
    - [[#org-projectile][Org Projectile]]
  - [[#misc][Misc]]

** Reference
I copy this from https://github.com/HaoZeke/dotdoom

** Aesthetic Packages
*** Dired Icons
Since treemacs already uses ~all-the-icons~ it is silly to not use them in
dired, from the [[https://github.com/domtronn/all-the-icons.el/wiki][all-the-icons wiki]].
#+BEGIN_SRC emacs-lisp
(package! all-the-icons-dired)
#+END_SRC
*** Wakatime
Not exactly aesthetic, but yeah, for stats.
#+BEGIN_SRC emacs-lisp
(package! wakatime-mode)
#+END_SRC
** Org Additions
*** Org Protocol Updates
This needs to be installed specially, [[https://github.com/alphapapa/org-protocol-capture-html][from this repo]].
#+BEGIN_SRC emacs-lisp
(package! org-protocol-capture-html
  :recipe (:host github
           :repo "alphapapa/org-protocol-capture-html"))
#+END_SRC
*** Org Noter
This is sort of more of a ~pdf-tools~ extension and it needs it's own ~biblatex~
setup and stuff as well so this might move into a tree of it's own.

#+BEGIN_SRC emacs-lisp
(package! org-noter)
#+END_SRC

This actually breaks the ~pdf-tools~ bindings.

*** Org kankan
#+begin_src emacs-lisp  :tangle yes
(package! org-kanban)
#+end_src

*** Org http
#+begin_src emacs-lisp
(package! ob-http)
(package! ob-restclient)

#+end_src
*** Org Roam
#+begin_src emacs-lisp :tangle yes
(package! org-roam-server)
#+end_src

*** Org Rifle
Technically a helm addition. Perfect for monolithic ~org~ files. More details
[[https://github.com/alphapapa/helm-org-rifle][here]].
#+BEGIN_SRC emacs-lisp
(package! helm-org-rifle)
#+END_SRC
*** Org Projectile
#+begin_src emacs-lisp :tangle yes
(package! org-projectile)
#+end_src

** Misc
#+BEGIN_SRC emacs-lisp
(package! sicp)
(package! w3m)
(package! ox-twbs)
#+END_SRC
