#!/bin/sh
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS

XDG_SESSION_TYPE=x11 
export XDG_SESSION_TYPE

# x11 resources
[ -r $HOME/.config/X11/xresources ] && xrdb -merge $HOME/.config/X11/xresources

# wm
vncconfig -nowin &
hsetroot -solid black
eval $(dbus-launch --sh-syntax)
#exec i3
xsetroot -cursor_name left_ptr

exec bspwm
