#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
XDG_SESSION_TYPE=x11;  export XDG_SESSION_TYPE
[ -r $HOME/.config/X11/xresources ] && xrdb -merge $HOME/.config/X11/xresources

hsetroot -solid black

#Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1

export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx
export QT_QPA_PLATFORMTHEME="qt5ct"

vncconfig -nowin &
i3 &

