#!/bin/sh
#unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS

XDG_SESSION_TYPE=x11 
export XDG_SESSION_TYPE

# x11 resources
[ -r $HOME/.config/X11/xresources ] && xrdb -merge $HOME/.config/X11/xresources

# IME

if [ -x "$(command -v fcitx5)" ]; then
    echo 'use fcitx5'
    export GTK_IM_MODULE=fcitx5
    export QT_IM_MODULE=fcitx5
    export XMODIFIERS=@im=fcitx5
    fcitx5 &  
elif [ -x "$(command -v fcitx)" ]; then
    echo 'use fcitx'
    export GTK_IM_MODULE=fcitx
    export QT_IM_MODULE=fcitx
    export XMODIFIERS=@im=fcitx
    fcitx -dr    
elif [ -x "$(command -v ibus-daemon)" ]; then
    echo 'use ibus'
    export GTK_IM_MODULE=xim
    export QT_IM_MODULE=xim  
    export XMODIFIERS=@im=ibus
    ibus-daemon -drx
fi

# wm
vncconfig -nowin &
hsetroot -solid black
eval $(dbus-launch --sh-syntax)
#exec i3
xsetroot -cursor_name left_ptr

exec bspwm
