# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$all\
$fill\
$username\
$hostname\
$line_break\
$character
"""
[username]
format = "[$user]($style) "

[hostname]
format = "[@](white bold) [$hostname]($style)"

[character] 
success_symbol = "[➜](bold green)" 

[package]
disabled = true

[gcloud]
disabled = true
