#!/usr/bin/env bash


##############################################################################
#                            GENERAL CONFIGURATION                           #
##############################################################################

bspc config border_width         1 
bspc config window_gap           2

bspc config top_padding          26
bspc config bottom_padding       0

# from https://draculatheme.com/bspwm/
bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true


bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

##############################################################################
#                                 WINDOW RULES                               #
##############################################################################
bspc rule -a Blueman-manager    state=floating
bspc rule -a KeePassXC          state=floating
bspc rule -a Zathura            state=tiled
bspc rule -a dolphin            state=floating

##############################################################################
#                                AUTOSTART APPS                              #
##############################################################################

$HOME/.config/bspwm/autostart.sh &

##############################################################################
#                                Monitors                                    #
##############################################################################

$HOME/.config/bspwm/monitor.sh &

